### ISSUE TITLE
pgtap tests: need to set the required input graph

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#1630]
**Is your feature request related to a problem? Please describe.**
The pgtap tests work on graphs that are based on the `edge_table` of [the sample data](https://docs.pgrouting.org/3.1/en/sampledata.html)

Some tests modify the graph for example [this test](https://github.com/pgRouting/pgrouting/blob/cd560142b48d92742d4fbf82e60326d91d1d1b30/pgtap/contraction/deadend/undirected/dijkstra-compare.sql#L5)

Normally that doesn't cause problems (hasn't caused a problem yet)
But currently I am working on some new functionality that adds more pgtap tests, that also modify the graph, and that is causing tests that are based on a unit value for `cost` `reverse_cost` (like tests that are general for type checking) to failing because the values of the edge_table costs do not have a unit value needed for them. ([see here](https://github.com/cvvergara/pgrouting/runs/1232514827?check_suite_focus=true#step:8:377) and the only changes are [these](https://github.com/pgRouting/pgrouting/commit/ca976897ae5b9122e97205af695904e927c7f0ed) new tests)

Which means that the "unit" tests changes on the database can affect another unit test in a different file, all the tests are done with one command `pg_prove` so we don't control the order in which they are done.

# TODO: recommended solution

## case 1
In general tests that use the original data from the sample data, add the `UPDATE` clause after the `plan` to restore to the original values of the sample data, making sure that the tests are done with the unit values for `costs`/`reverse_cost`
```
SELECT plan(11);
UPDATE edge_table SET cost = sign(cost), reverse_cost = sign(reverse_cost);
```
## case 2
Tests that modify the sample data as follows:
From:
```
UPDATE edge_table SET cost = cost + 0.001 * id * id, reverse_cost = reverse_cost + 0.001 * id * id;
```
to:
```
UPDATE edge_table SET cost = sign(cost) + 0.001 * id * id, reverse_cost = sign(reverse_cost) + 0.001 * id * id;
```
That will avoid that an `UPDATE` in a *test1*  then when `test2` that has another `UPDATE` will not have the expected working values for the unit test.

Remember a unit test has a fixed expected result given a fixed expected input.

# TODO where
As this is an enhancent on  the unit tests no milestone is open, but this needs to be done before the new releases.
- [x] on 3.0  (3.0.3) on branch release-3.0
- [x] on 3.1  (3.1.1) on branch master
- [x] on 3.2-dev (3.2.0-dev) on branch develop
